# Generated by Django 4.2.16 on 2025-03-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sitee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_num', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('sitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitee.sitee')),
            ],
        ),
    ]
